-- docs/supabase/observability_fn_metrics.sql
-- Observability: function-level metrics and RLS denial logging
-- Transaction-safe migration (no CONCURRENTLY indexes).
-- Verifications (run in order after applying):
--   select to_regclass('public.fn_metrics'), to_regclass('public.rls_denials');
--   select public.log_fn_metric('smoke','ok',12,'{}'::jsonb);
--   select * from public.fn_metrics order by created_at desc limit 1;
--   select * from public.v_fn_p95_24h;
--   select * from public.v_fn_status_24h;

begin;

-- 1) Tables
create table if not exists public.fn_metrics (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  fn_name       text not null,
  status        text not null,
  duration_ms   integer not null check (duration_ms >= 0),
  ctx           jsonb not null default '{}'::jsonb,
  user_id       uuid null,
  org_id        uuid null,
  err_code      text null,
  err_text      text null
);

create index if not exists idx_fn_metrics_created_at on public.fn_metrics (created_at);
create index if not exists idx_fn_metrics_fn_name on public.fn_metrics (fn_name);
create index if not exists idx_fn_metrics_status_created on public.fn_metrics (status, created_at);
create index if not exists idx_fn_metrics_ctx_gin on public.fn_metrics using gin (ctx);

comment on table public.fn_metrics is 'Function call metrics for observability (per-call status, duration, minimal context).';

create table if not exists public.rls_denials (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  object_name   text not null,
  action        text not null,
  reason        text not null,
  user_id       uuid null,
  ctx           jsonb not null default '{}'::jsonb
);

create index if not exists idx_rls_denials_created_at on public.rls_denials (created_at);
create index if not exists idx_rls_denials_object on public.rls_denials (object_name);
create index if not exists idx_rls_denials_ctx_gin on public.rls_denials using gin (ctx);

comment on table public.rls_denials is 'Audit log of RLS denials (optional manual logging from app/rpc).';

-- 2) Function to log metrics
-- SECURITY DEFINER so it can write even if caller cannot insert directly; lock search_path.
create or replace function public.log_fn_metric(
  p_fn_name text,
  p_status text,
  p_duration_ms integer,
  p_ctx jsonb default '{}'::jsonb,
  p_err_code text default null,
  p_err_text text default null
) returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_claims jsonb := nullif(current_setting('request.jwt.claims', true), '')::jsonb;
  v_user uuid := auth.uid();
  v_org uuid := null;
begin
  if v_claims ? 'org_id' then
    begin
      v_org := (v_claims->>'org_id')::uuid;
    exception when others then
      v_org := null; -- ignore bad claim
    end;
  end if;

  insert into public.fn_metrics(fn_name, status, duration_ms, ctx, user_id, org_id, err_code, err_text)
  values (p_fn_name, p_status, greatest(0, coalesce(p_duration_ms, 0)), coalesce(p_ctx, '{}'::jsonb), v_user, v_org, p_err_code, p_err_text);
end;
$$;

comment on function public.log_fn_metric(text, text, integer, jsonb, text, text) is 'Observability: insert a function metric row; stamps auth.uid() and org_id claim if present.';

-- 3) Views over last 24h
create or replace view public.v_fn_p95_24h as
select
  fn_name,
  count(*) as calls,
  percentile_cont(0.95) within group (order by duration_ms) as p95_ms,
  min(duration_ms) as p_min_ms,
  max(duration_ms) as p_max_ms
from public.fn_metrics
where created_at >= now() - interval '24 hours' and status = 'ok'
group by fn_name
order by p95_ms desc nulls last;

create or replace view public.v_fn_status_24h as
select
  fn_name,
  status,
  count(*) as calls
from public.fn_metrics
where created_at >= now() - interval '24 hours'
group by fn_name, status
order by fn_name, status;

-- 4) Grants: narrow PUBLIC, allow reads to authenticated/service_role; execute to those roles.
-- Note: these roles exist in Supabase. Adjust if needed.
revoke all on table public.fn_metrics from public;
revoke all on table public.rls_denials from public;
revoke all on view public.v_fn_p95_24h from public;
revoke all on view public.v_fn_status_24h from public;
revoke all on function public.log_fn_metric(text, text, integer, jsonb, text, text) from public;

grant select on table public.fn_metrics to authenticated, service_role;
grant select on table public.rls_denials to authenticated, service_role;
grant select on table public.v_fn_p95_24h to authenticated, service_role;
grant select on table public.v_fn_status_24h to authenticated, service_role;
grant execute on function public.log_fn_metric(text, text, integer, jsonb, text, text) to authenticated, service_role;

commit;
