-- 2025-09-16_ops_metrics.sql
-- Create a lightweight ops_metrics table for generic metrics ingestion from Edge Functions/jobs.
-- Matches the usage pattern in metrics_push function helper.

begin;

set search_path = public;

create table if not exists public.ops_metrics (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  metric      text not null,
  value       numeric not null,
  dims        jsonb not null default '{}'::jsonb
);

create index if not exists idx_ops_metrics_metric_time on public.ops_metrics(metric, created_at desc);
create index if not exists idx_ops_metrics_dims_gin on public.ops_metrics using gin (dims);

comment on table public.ops_metrics is 'Generic operational metrics; dimensions stored as jsonb (e.g., env, fn, queue).';

-- Grants: no PUBLIC access; allow reads to authenticated/service_role; writes typically via service_role only
revoke all on table public.ops_metrics from public;
grant select on table public.ops_metrics to authenticated, service_role;
-- Optional: if you want authenticated writers (rare), grant insert explicitly; default is service-role writes via Edge Functions
-- grant insert on table public.ops_metrics to authenticated;

commit;
