name: Build Desktop Apps

on:
  push:
    branches: [main, develop]
    tags:
      - 'desktop-v*'

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        role: [owner-operator, fleet-manager]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build Windows
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON: ${{ secrets.SUPABASE_ANON }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        shell: bash
        run: |
          DEFAULT_ROLE="${{ matrix.role == 'owner-operator' && 'owner_operator' || 'fleet_manager' }}"
          flutter build windows --release \
            --dart-define=SUPABASE_URL="$SUPABASE_URL" \
            --dart-define=SUPABASE_ANON="$SUPABASE_ANON" \
            --dart-define=SENTRY_DSN="$SENTRY_DSN" \
            --dart-define=APP_VERSION="${GITHUB_REF#refs/*/}" \
            --dart-define=GIT_COMMIT="${GITHUB_SHA:0:7}" \
            --dart-define=RELEASE_CHANNEL="production" \
            --dart-define=USE_MOCK_DATA="false" \
            --dart-define=DEFAULT_ROLE="$DEFAULT_ROLE"
      
      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.role }}-windows
          path: build/windows/x64/runner/Release/

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        role: [owner-operator, fleet-manager]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build macOS
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON: ${{ secrets.SUPABASE_ANON }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          DEFAULT_ROLE="${{ matrix.role == 'owner-operator' && 'owner_operator' || 'fleet_manager' }}"
          flutter build macos --release \
            --dart-define=SUPABASE_URL="$SUPABASE_URL" \
            --dart-define=SUPABASE_ANON="$SUPABASE_ANON" \
            --dart-define=SENTRY_DSN="$SENTRY_DSN" \
            --dart-define=APP_VERSION="${GITHUB_REF#refs/*/}" \
            --dart-define=GIT_COMMIT="${GITHUB_SHA:0:7}" \
            --dart-define=RELEASE_CHANNEL="production" \
            --dart-define=USE_MOCK_DATA="false" \
            --dart-define=DEFAULT_ROLE="$DEFAULT_ROLE"
      
      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.role }}-macos
          path: build/macos/Build/Products/Release/

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role: [owner-operator, fleet-manager]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build Linux
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON: ${{ secrets.SUPABASE_ANON }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          DEFAULT_ROLE="${{ matrix.role == 'owner-operator' && 'owner_operator' || 'fleet_manager' }}"
          flutter build linux --release \
            --dart-define=SUPABASE_URL="$SUPABASE_URL" \
            --dart-define=SUPABASE_ANON="$SUPABASE_ANON" \
            --dart-define=SENTRY_DSN="$SENTRY_DSN" \
            --dart-define=APP_VERSION="${GITHUB_REF#refs/*/}" \
            --dart-define=GIT_COMMIT="${GITHUB_SHA:0:7}" \
            --dart-define=RELEASE_CHANNEL="production" \
            --dart-define=USE_MOCK_DATA="false" \
            --dart-define=DEFAULT_ROLE="$DEFAULT_ROLE"
      
      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.role }}-linux
          path: build/linux/x64/release/bundle/
