name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: supabase/postgres:15.1.0.117
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Run unit tests
        run: flutter test --coverage --reporter expanded
        env:
          SUPABASE_URL: ${{ secrets.TEST_SUPABASE_URL }}
          SUPABASE_ANON: ${{ secrets.TEST_SUPABASE_ANON }}

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local
        run: supabase start

      - name: Set Supabase anon key
        shell: bash
        run: |
          if [ -n "${{ secrets.TEST_SUPABASE_ANON }}" ]; then
            echo "ANON_KEY=${{ secrets.TEST_SUPABASE_ANON }}" >> $GITHUB_ENV
          else
            if command -v jq >/dev/null 2>&1; then
              :
            else
              sudo apt-get update && sudo apt-get install -y jq
            fi
            KEY_FILE="$(pwd)/supabase/.temp/keys.json"
            if [ -f "$KEY_FILE" ]; then
              echo "ANON_KEY=$(jq -r '.anon' \"$KEY_FILE\")" >> $GITHUB_ENV
            else
              echo "ANON_KEY=anon-key" >> $GITHUB_ENV
            fi
          fi

      - name: Run integration tests with real Supabase
        run: flutter test test/integration/supabase_integration_test.dart --dart-define=SUPABASE_URL=http://localhost:54321 --dart-define=SUPABASE_ANON=$ANON_KEY

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info

      - name: Stop Supabase
        run: supabase stop
