name: Promote between environments

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Environment to promote to (staging|canary|prod)'
        required: true
        default: 'staging'
      canaryPercent:
        description: 'For canary, percentage of traffic/users to enable (0-100)'
        required: false
        default: '10'

permissions:
  contents: read
  id-token: write

jobs:
  promote:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Select project by target
        id: select
        run: |
          case "${{ inputs.target }}" in
            staging)
              echo "project=${{ secrets.SUPABASE_STAGING_PROJECT_ID }}" >> $GITHUB_OUTPUT;;
            canary)
              echo "project=${{ secrets.SUPABASE_CANARY_PROJECT_ID }}" >> $GITHUB_OUTPUT;;
            prod)
              echo "project=${{ secrets.SUPABASE_PROD_PROJECT_ID }}" >> $GITHUB_OUTPUT;;
            *) echo "Unknown target"; exit 1;;
          esac

      - name: Link project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          if [ -z "${{ steps.select.outputs.project }}" ] || [ -z "$SUPABASE_ACCESS_TOKEN" ]; then
            echo "Missing Supabase secrets for target ${{ inputs.target }}"; exit 1
          fi
          supabase link --project-ref "${{ steps.select.outputs.project }}"

      - name: Push DB migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase db push

      - name: Deploy Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase functions deploy --project-ref "${{ steps.select.outputs.project }}" || true

      - name: Apply canary flag percentage (no-op for non-canary)
        if: inputs.target == 'canary'
        run: |
          echo "Would apply canary percent=${{ inputs.canaryPercent }} via feature flags or routing configuration"
