name: Edge Functions Smoke Tests

on:
  schedule:
    - cron: "*/20 * * * *" # every 20 minutes
  workflow_dispatch: {}

jobs:
  edge_smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.SUPABASE_FUNCTIONS_URL }}" ]; then
            echo "No SUPABASE_FUNCTIONS_URL configured; skipping."; exit 0; fi
          if [ -z "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" ]; then
            echo "No SUPABASE_SERVICE_ROLE_KEY configured; skipping."; exit 0; fi
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
      - name: Healthz (GET)
        env:
          FUNCTIONS_URL: ${{ secrets.SUPABASE_FUNCTIONS_URL }}
          SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          set -e
          RES=$(curl -fsSL -H "Authorization: Bearer $SERVICE_ROLE" "$FUNCTIONS_URL/healthz")
          echo "$RES" | jq '.'
          OK=$(echo "$RES" | jq -r '.ok')
          if [ "$OK" != "true" ] && [ "$OK" != "false" ]; then
            echo "Invalid schema for healthz (missing ok)"; exit 1; fi
      - name: Notify alerts (POST)
        env:
          FUNCTIONS_URL: ${{ secrets.SUPABASE_FUNCTIONS_URL }}
          SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          set -e
          RES=$(curl -fsSL -X POST -H "Authorization: Bearer $SERVICE_ROLE" "$FUNCTIONS_URL/notify-alerts")
          echo "$RES" | jq '.'
          DEL=$(echo "$RES" | jq -r '.delivered')
          if [ -z "$DEL" ]; then echo "Invalid schema for notify-alerts (missing delivered)"; exit 1; fi
      - name: Weekly SLO report (POST)
        env:
          FUNCTIONS_URL: ${{ secrets.SUPABASE_FUNCTIONS_URL }}
          SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          set -e
          RES=$(curl -fsSL -X POST -H "Authorization: Bearer $SERVICE_ROLE" "$FUNCTIONS_URL/weekly-slo-report")
          echo "$RES" | jq '.'
          OK=$(echo "$RES" | jq -r '.ok')
          if [ "$OK" != "true" ]; then echo "Invalid schema for weekly-slo-report (ok!=true)"; exit 1; fi
