name: PR Comment Checks
on: [pull_request]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || "";
            const needs = [];
            if (!/Probe results:\s*p50=.*p95=.*/i.test(body)) needs.push("Probe results (p50/p95)");
            if (!/Runbook updated:\s*`docs\/runbooks\//i.test(body)) needs.push("Runbook link");
            if (!/Feature flag key/i.test(body)) needs.push("Feature flag key");
            if (needs.length) {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: `⚠️ Missing items: ${needs.join(", ")}`
              });
            }
