name: Release Gate + Artifacts
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
  id-token: write
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup deps
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client jq
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.59.1
          curl -sSfL https://github.com/sigstore/cosign/releases/download/v2.4.1/cosign-linux-amd64 -o cosign && chmod +x cosign && sudo mv cosign /usr/local/bin/cosign

      - name: Run release gate
        run: make release_gate
        env:
          FUNC_URL: ${{ secrets.FUNC_URL }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}

      - name: Build evidence
        run: make evidence

      - name: Build Sales bundle
        run: make sales_bundle
        env:
          FUNC_URL: ${{ secrets.FUNC_URL }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          ORG_ID: ${{ secrets.SALES_CASE_ORG_ID }}

      - name: Generate release notes
        run: make release_notes
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}

      - name: (Optional) Sign evidence bundle with keyless cosign
        if: ${{ vars.ENABLE_COSIGN == 'true' }}
        run: |
          LATEST=$(ls -1t evidence/*.tgz 2>/dev/null | head -n1)
          if [ -n "$LATEST" ]; then
            cosign sign-blob --yes --bundle "${LATEST}.bundle" "$LATEST"
          else
            echo "No evidence bundle found"
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts-${{ github.ref_name }}
          path: |
            evidence/*.tgz
            evidence/**/*.tgz
            sales/*.html
            sales/*-kpis.json
            NOTES.md
            evidence/*.bundle
          if-no-files-found: error
          retention-days: 30
