name: Runbooks Validation

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  runbooks_check:
    name: runbooks_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (if any)
        run: |
          if [ -f package-lock.json ]; then npm ci --ignore-scripts; fi

      - name: Validate runbooks
        run: |
          node scripts/runbooks.js
