name: Schema Contract Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  schema_contract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci --ignore-scripts; else npm i --ignore-scripts; fi

      - name: Run RPC/View contract tests (PostgREST)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          node test_supabase_rpc.mjs || node test_rpcs.js

      - name: Upload logs (optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: schema-contract-logs-${{ github.run_id }}
          path: |
            ./contract-logs/**/*
            ./contract-logs/*
