name: Secret Scan (Gitleaks)

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f4634a9a56a8b5f807a1f41f2d6d2c07 # v4.1.6
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@2a8a5a1356608586c019c557c7c1e5ab24e41b8c # v2.3.7
        with:
          args: "detect --no-banner --redact --exit-code 1"
