name: SQL Lint – Billing

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  billing_sql_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install psql
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Run billing SQL assertions
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          if [ -z "$SUPABASE_DB_URL" ]; then
            echo "No SUPABASE_DB_URL configured; skipping billing SQL checks."; exit 0; fi
          psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f docs/ci/BILLING_SQL_CHECKS.sql
